# Generated by Django 3.0.3 on 2020-02-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
