# Generated by Django 3.0.3 on 2020-02-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulist_app', '0002_auto_20200228_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
